### ISSUE TITLE
GEF not triggering?

### ISSUE THREAD

**Issue by kyleholgate** [miraclewhips/geoguessr-event-framework#1]
I'm trying to use GEF + GeoGuessr Training mode but I'm finding it's not working, the only thing it does is change the compass color.

After some debugging I've traced it down to the following - 

The GEF gets created in the Training script, but the GEF never triggers the `round_start` event.

```javascript
GeoGuessrEventFramework.init().then(GEF => {
	console.log('GeoGuessr Training Mode initialised.');
        // this loads with just the default state
        console.log('GEF initialized', GEF);

        // this never triggers
	GEF.events.addEventListener('round_start', (state) => {
		addSettingsButtonsToRound();
	});
```

Looking at the GEF's initialization script, it's looking for a div with a class `in-game_root__` which does indeed exist, but it doesn't seem to find it? I disabled ad blockers and I've seen people in [this YouTube video](https://www.youtube.com/watch?v=D06N3zE5bIY) say they've had this same issue starting ~2 months ago (also around the last time the GEF was updated) and it has happened on multiple browsers.

Any ideas? I'm not a Javascript native.

**Comment by miraclewhips** [comment]
The script is working fine for me. Are you using the latest version?
